Create ProgressMainWindow
paskino/qt-elements pull request #71
Opened 2023-04-11 14:25 UTC by lauramurgatroyd

2023-04-17 10:02 UTC, paskino requested changes

2023-04-17 10:03 UTC, lauramurgatroyd commented on eqt/ui/ProgressMainWindow.py
> +        pass
Yes, in the docstring it tells the user to override this in a child class

2023-04-18 16:07 UTC, lauramurgatroyd commented on eqt/ui/ProgressMainWindow.py
> +        self.progress_windows = {}
done

2023-04-18 16:07 UTC, lauramurgatroyd commented
Updated to make progress_windows a property and renamed the classes to:
- MainWindowWithSessionManagement
- MainWindowWithProgressDialogs

2023-04-19 16:10 UTC, lauramurgatroyd commented
Removed addToMenu method

2023-04-20 07:10 UTC, paskino approved these changes

2023-04-20 07:57 UTC, merged